INSERT INTO clientes (nombre_cliente, razon_social, formato_factura, activo)
SELECT client_name, client_name, TRUE, TRUE
FROM (
  SELECT 'NISSEI ADVANTECH MEXICO, S.A DE C.V.' AS client_name
  UNION ALL SELECT 'NORTH AMERICAN RADIATORS S DE RL DE CV'
  UNION ALL SELECT 'NUCOR COIL FINISH MONTERREY'
  UNION ALL SELECT 'OMAR SALDIVAR'
  UNION ALL SELECT 'PALACIOS CONSTRUCCIONES Y MAQUINARIAS S'
  UNION ALL SELECT 'PANDUIT'
  UNION ALL SELECT 'PARAMOUNT DIE MEXICO S.DE R.L.'
  UNION ALL SELECT 'PERFECTOOLS'
  UNION ALL SELECT 'PERFEKTOOLS S DE RL DE CV'
  UNION ALL SELECT 'PERI MANUFACTURAS DE RL DE CV'
  UNION ALL SELECT 'PETROSEAL, S.A DE C.V.'
  UNION ALL SELECT 'PEXCO'
  UNION ALL SELECT 'PROLAMSA'
  UNION ALL SELECT 'PROMEC SA DE CV'
  UNION ALL SELECT 'PROTMEC'
  UNION ALL SELECT 'RANMAL MANUFACTURING'
  UNION ALL SELECT 'RASSINI'
  UNION ALL SELECT 'RAUL GODINEZ (PRIMO SR JAVIER)'
  UNION ALL SELECT 'RC LAMINAS'
  UNION ALL SELECT 'RC RACK'
  UNION ALL SELECT 'REGAL REXNORD CORPORATION'
  UNION ALL SELECT 'REGIOPYTSA'
  UNION ALL SELECT 'RHP INDUSTRIAL, SA DE CV'
  UNION ALL SELECT 'RIASA'
  UNION ALL SELECT 'ROBERTO FLORES'
  UNION ALL SELECT 'ROBERTO SANCHEZ'
  UNION ALL SELECT 'ROSENBERGER'
  UNION ALL SELECT 'RP SA DE CV'
  UNION ALL SELECT 'SACHEM TECHNOLOGY DE MEXICO'
) AS legacy_clients
WHERE NOT EXISTS (
  SELECT 1
    FROM clientes
   WHERE UPPER(nombre_cliente) = UPPER(legacy_clients.client_name)
);
